TAB-9521:remove unused main methods from codebase
Terracotta-OSS/dso pull request #153
Opened 2024-08-30 14:28 UTC by devlg75

2024-08-30 19:45 UTC, cljohnso requested changes
Looks good other than the `/` you noted in chat.

This commit stream needs to go into main, 4.4.1, 4.4.0, and possibly 4.3.10.  Is this commit stream properly daggy?

2024-08-30 19:45 UTC, cljohnso commented on terracotta-kit/src/test/java/org/terracotta/kit/EhcacheAllIT.java
> +            Assert.assertNotNull(urlClassLoader.findResource("/Version.info"));
Just a reminder to alter this ...

2024-09-02 11:53 UTC, devlg75 commented on terracotta-kit/src/test/java/org/terracotta/kit/EhcacheAllIT.java
> +            Assert.assertNotNull(urlClassLoader.findResource("/Version.info"));
done.

2024-09-02 11:54 UTC, devlg75 commented
> Looks good other than the `/` you noted in chat.
> 
> This commit stream needs to go into main, 4.4.1, 4.4.0, and possibly 4.3.10. Is this commit stream properly daggy?

this commit is daggy, I'll raise PR's for other branches as well.

2024-09-03 12:46 UTC, cljohnso approved these changes

2024-09-03 12:50 UTC, merged